name: Terraform Deploy

on:
  push:
    branches:
      - main   # or whichever branch you deploy from
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest  # You get 30 hours per month free on GitHub-hosted runners. For windows it is 15. Linux is cheaper.

    permissions:
      id-token: write   # required for OIDC auth
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0   # Put in the version you want. 
          # Your .terraform.lock.hcl will ensure the providers are the same version.
          # Like like hashicorp/aws, hashicorp/random, etc
          # This line above decides which terraform version to use.

      # Option 1: If using access keys
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'   # only auto-apply on main
        run: terraform apply -input=false -auto-approve tfplan
